<?php  ?>
<nav class="navbar navbar-dark bg-dark">
    <span class="navbar-brand mb-0 h1">Show do Bilhão</span>
    <!-- <a href="#">Sair</a> -->
    <form class="form-inline" action="" method="post">
        <input class="form-control mr-sm-2" type="text" name="nome" placeholder="Seu nome" aria-label="name" oninvalid="this.setCustomValidity('Digite seu nome para jogar')" required>
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Jogar</button>
    </form>
</nav>