<?php
            $perguntas = [];
            $alternativas = [];
            $corretas = [];
            for ($i=0; $i<20; $i++) $alternativas[$i]=[];

            $perguntas[0] = "Em qual país foi inventado o brinquedo LEGO?";
            $alternativas[0][0] = "Estados Unidos";
            $alternativas[0][1] = "Japão";
            $alternativas[0][2] = "Itália";
            $alternativas[0][3] = "Dinamarca";
            $corretas[0] = 3;

            $perguntas[1] = "Qual desses astros ainda está vivo (24/05/2017)?";
            $alternativas[1][0] = "Elvis Presley";
            $alternativas[1][1] = "Paul McCartney";
            $alternativas[1][2] = "Michael Jackson";
            $alternativas[1][3] = "Prince";
            $corretas[1] = 1;

            $perguntas[2] = "Onde fica o Oceano Índico?";
            $alternativas[2][0] = "No Pólo Norte";
            $alternativas[2][1] = "Perto da Índia";
            $alternativas[2][2] = "Entre a Europa e a África";
            $alternativas[2][3] = "Ao redor da Austrália";
            $corretas[2] = 1;

            $perguntas[3] = "VHDL é uma linguagem de:";
            $alternativas[3][0] = "Descrição";
            $alternativas[3][1] = "Programação";
            $alternativas[3][2] = "Tortura";
            $alternativas[3][3] = "Nenhuma das anteriores";
            $corretas[3] = 2;

            $perguntas[4] = "Por qual motivo você deve sempre identar seu código?";
            $alternativas[4][0] = "Os veteranos vão te matar se não fizer isso";
            $alternativas[4][1] = "Vale Ponto";
            $alternativas[4][2] = "As curvas ficam sexy";
            $alternativas[4][3] = "Todas as anteriores";
            $corretas[4] = 3;

            $perguntas[5] = "Qual dos seguinte mitos sobre o Honda é verdade?";
            $alternativas[5][0] = "Ele mora sozinho no meio do nada";
            $alternativas[5][1] = "Ele teleporta";
            $alternativas[5][2] = "Ele mora com ninguém sabe quantos caras";
            $alternativas[5][3] = "Todas as anteriores";
            $corretas[5] = 3;

            $perguntas[6] = "Quando improvisando um quiz para um exercício, você usa skillz de:";
            $alternativas[6][0] = "Infação";
            $alternativas[6][1] = "Migué";
            $alternativas[6][2] = "Criatividade";
            $alternativas[6][3] = "McGyverismo";
            $corretas[6] = 1;

            $perguntas[7] = "Se a resposta dessa pergunta fosse a segunda bolinha, qual você marcaria?";
            $alternativas[7][0] = "A primeira";
            $alternativas[7][1] = "A terceira";
            $alternativas[7][2] = "A segunda";
            $alternativas[7][3] = "A última";
            $corretas[7] = 2;

            $perguntas[8] = "Qual desses jogos é infame por ser difícil?";
            $alternativas[8][0] = "Super Mario World para SNES";
            $alternativas[8][1] = "O show do Milhão";
            $alternativas[8][2] = "Dark Souls para PS3, PC e XB360";
            $alternativas[8][3] = "The Legend of Zelda: Ocarina of Time para o N64";
            $corretas[8] = 2;

            $perguntas[9] = "8) Quantas perguntas já foram feitas?";
            $alternativas[9][0] = "10";
            $alternativas[9][1] = "9";
            $alternativas[9][2] = "8";
            $alternativas[9][3] = "7";
            $corretas[9] = 0;

            $perguntas[10] = "Em qual século Gandhi nasceu?";
            $alternativas[10][0] = "XIX";
            $alternativas[10][1] = "XV";
            $alternativas[10][2] = "XII";
            $alternativas[10][3] = "Nenhum. Ele é um personagem mítico";
            $corretas[10] = 0;

            $perguntas[11] = "Onde a pizza foi inventada?";
            $alternativas[11][0] = "Itália";
            $alternativas[11][1] = "Grécia";
            $alternativas[11][2] = "Estados Unidos";
            $alternativas[11][3] = "Austrália";
            $corretas[11] = 1;

            $perguntas[12] = "Em qual continente fica a Áustria?";
            $alternativas[12][0] = "África";
            $alternativas[12][1] = "Oceania";
            $alternativas[12][2] = "América Central";
            $alternativas[12][3] = "Europa";
            $corretas[12] = 3;

            $perguntas[13] = "O Mediterrâneo é...";
            $alternativas[13][0] = "Uma cordilheira";
            $alternativas[13][1] = "Um mar";
            $alternativas[13][2] = "Um lago";
            $alternativas[13][3] = "Uma montanha";
            $corretas[13] = 1;

            $perguntas[14] = "Qual das seguintes músicas NÃO é dos Beatles?";
            $alternativas[14][0] = "Cry, Baby, Cry";
            $alternativas[14][1] = "Start me Up";
            $alternativas[14][2] = "Ob-la-di, Ob-la-da";
            $alternativas[14][3] = "Yellow Submarine";
            $corretas[14] = 1;

            $perguntas[15] = "Qual das seguintes bandas NÃO é inglesa?";
            $alternativas[15][0] = "The Rolling Stones";
            $alternativas[15][1] = "The Beatles";
            $alternativas[15][2] = "Led Zeppelin";
            $alternativas[15][3] = "The White Stripes";
            $corretas[15] = 3;

            $perguntas[16] = "O filme Shrek é de qual estúdio de animação?";
            $alternativas[16][0] = "DreamWorks";
            $alternativas[16][1] = "Disney";
            $alternativas[16][2] = "Sony";
            $alternativas[16][3] = "Pixar";
            $corretas[16] = 0;

            $perguntas[17] = "Qual é o nome do companheiro de Sherlock Holmes?";
            $alternativas[17][0] = "Moriarty";
            $alternativas[17][1] = "Poirot";
            $alternativas[17][2] = "Watson";
            $alternativas[17][3] = "Lupin";
            $corretas[17] = 2;

            $perguntas[18] = "Mas o mago é...";
            $alternativas[18][0] = "Poderoso";
            $alternativas[18][1] = "Fedido";
            $alternativas[18][2] = "Dumbledore";
            $alternativas[18][3] = "Implacável";
            $corretas[18] = 3;

            $perguntas[19] = "QUEM é \"O Senhor dos Anéis\" ao qual o título dos filmes e livros se refere?";
            $alternativas[19][0] = "Frodo";
            $alternativas[19][1] = "Sauron";
            $alternativas[19][2] = "Gandalf";
            $alternativas[19][3] = "Gollum";
            $corretas[19] = 1;
?>
<?php
            function carregaPergunta($num){
                global $perguntas;
                global $alternativas;
                global $corretas;

                $numReal = $num+1;
                ?> <p>Pergunta <?= $numReal ?> de 20 <?php
                if (!isset($_SESSION["login"])&&!isset($_POST["login"])){  //Se não houver alguém logado
                    header ("Location: login.php");
                }
                else {
                    $_SESSION["login"] = $_POST["login"];
                    $id = $_COOKIE["id"];
                    $lastScore = $_COOKIE["lastScore"];
                    $lastDate = $_COOKIE["lastDate"];
                    $_COOKIE["score"] = 0;
                }
                
                if ($num >= 20){
                    ?>
                    <h1>VOCÊ CHEGOU AO FIM!!!</h1>
                    <a href="fim.php">Ver Resultados</a>
                    <?php
                }
                else {
                    if ($num !=0) {
                        echo $_COOKIE["score"];
                        $numAnterior = $num-1;
                        $resposta = $_POST["$numAnterior"];
                        if ($resposta != $corretas[$numAnterior]) {
                            ?>
                            <h1>Você errou... :(</h1>
                            <a href="fim.php">Ver Resultados</a>
                  <?php }
                        else {
                           $_COOKIE["score"]; ?>
                            <h1><?php echo $perguntas[$num] ?></h1>
                            <FORM name="resposta" method="post" action="perguntas.php?num=<?php echo $num+1?>">
                                <Input type="hidden" name="num" value=<?= $num ?>>
                                <Input type = 'Radio' name = "<?= $num ?>" value=0 required>
                                    <?php echo $alternativas[$num][0] ?>
                                    <br>
                                <Input type = 'Radio' name = "<?= $num ?>" value=1 required>
                                    <?php echo $alternativas[$num][1] ?>
                                    <br>
                                <Input type = 'Radio' name = "<?= $num ?>" value=2 required>
                                    <?php echo $alternativas[$num][2] ?>
                                    <br>
                                <Input type = 'Radio' name = "<?= $num ?>" value=3 required>
                                    <?php echo $alternativas[$num][3] ?>
                                    <br>
                                <br>
                                <Input type="submit" value="Próxima!">
                            </FORM>
                            <h2>Pergunta <?= $num?> de 20</h2>
                  <?php }
                    } //Deve ter um jeito mais eficiente de fazer isso sem repetir o código do form
                    else { ?>
                        <h1><?php echo $perguntas[$num] ?></h1>
                        <FORM name="resposta" method="post" action="perguntas.php?num=<?php echo $num+1?>">
                            <Input type="hidden" name="num" value=<?= $num ?>>
                            <Input type = 'Radio' name = "<?= $num ?>" value=0 required>
                                <?php echo $alternativas[$num][0] ?>
                                <br>
                            <Input type = 'Radio' name = "<?= $num ?>" value=1 required>
                                <?php echo $alternativas[$num][1] ?>
                                <br>
                            <Input type = 'Radio' name = "<?= $num ?>" value=2 required>
                                <?php echo $alternativas[$num][2] ?>
                                <br>
                            <Input type = 'Radio' name = "<?= $num ?>" value=3 required>
                                <?php echo $alternativas[$num][3] ?>
                                <br>
                            <br>
                            <Input type="submit" value="Próxima!">
                        </FORM>
              <?php }
                }
            } ?>


<?php
            function carregaPerguntaConceito($num){
                global $perguntas;
                global $alternativas;
                ?>
                <h1><?php echo $perguntas[$num] ?></h1>
                <FORM name="resposta" method="post">
                    <Input type = 'Radio' name = "<?php echo $num ?>" value=0>
                        <?php echo $alternativas[$num][0] ?>
                        <br>
                    <Input type = 'Radio' name = "<?php echo $num ?>" value=1>
                        <?php echo $alternativas[$num][1] ?>
                        <br>
                    <Input type = 'Radio' name = "<?php echo $num ?>" value=2>
                        <?php echo $alternativas[$num][2] ?>
                        <br>
                    <Input type = 'Radio' name = "<?php echo $num ?>" value=3>
                        <?php echo $alternativas[$num][3] ?>
                        <br>
                </FORM>
      <?php } ?>