<?php
    require('question.inc');
    $data = array(
    new Question(
        'Como você desbloqueia a era 1 no SevTech: Ages?',
        array('A) Matando o boss to Totemic',
            'B) Construindo um forno de fundição',
            'C) Terminado o ritual do AbyssalCraft',
            'D) Fazendo sua primeira Crafting Table'),
        1),
    new Question(
        'Qual é a progressão dos materiais metálicos',
        array('A) Cobre -> Bronze -> Ferro',
            'B) Bronze -> Cobre -> Ferro',
            'C) Ferro -> Bronze -> Cobre',
            'D) Cobre -> Ferro -> Bronze'),
        0),
    new Question(
        'Qual é o mod responsável pela customização de equipamento?',
        array('A) AstralSorcery',
            'B) Tinker\'s Construct ',
            'C) SpartanWeaponry',
            'D) Immersive Engineering'),
        1)
    );
?>