<hr>
<form action='auth.php' method='POST'>
    <fieldset>
        <legend>Login</legend>
        <label for='user'>Usuario</label>
        <input type='text' name='user'></input><br>
        <label for='passwd'>Senha</label>
        <input type='password' name='passwd'></input><br>
        <input type='submit' value='Entrar' />
    </fieldset>
</form>

<p>Não tem conta? <a href='cadastro.php'>Crie a sua agora.</a></p>
<hr>