<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Game Over!</title>
</head>
<body>
    <h1>
        GAME OVER!
    </h1>
    <h3>
        VOCÊ PERDEU! Seus bolsos estão tão vazios quanto quando você veio.
    </h3>
    <form action="perguntas.php" method="get">
        <input type="hidden" name="id" value="0">
        <input type="submit" value="Tentar Novamente">
    </form>
</body>
</html>