<!DOCTYPE html>
<html>

    <head>
        <title>Game Over!</title>
    </head>

    <body>
        <h1>GAME OVER!</h1>
        <h3>
            VOCÊ PERDEU! Seus bolsos estão tão vazios quanto quando você veio.
        </h3>
        <form action="index.php" method="get">
            <input type="hidden" name="action" value="question" />
            <input type="submit" value="Tentar Novamente" />
        </form>
    </body>

</html>