<!DOCTYPE html>
<html>
    <head>
        <title>Game Over!</title>
    </head>
    <body>
        <h1>
            VOCÊ GANHOU!
        </h1>
        <h3>
            VOCÊ GANHOU E FICOU MILIONÁRIO! Súbitamente a parte da família que você nunca conversou está tendo muito prazer em contatá-lo.
        </h3>
        <form action="index.php" method="get">
            <input type="hidden" name="action" value="question">
            <input type="submit" value="Jogar Novamente">
        </form>
</body>
</html>