<head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css"  href="style.css" />
        <title>Clarisse Scofield</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
            
        <style type="text/css">#title,#glyphs h1{font-family:"Open Sans Condensed Light"}</style>    
        
</head>