<html>
        <head>
            <title>Jogo do Bilhão</title>
            <meta charset="utf-8">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" type="text/css" href="index.css">
        </head>
        <body>
            <h3 id="comeco">Bem Vindo(a) ao</h3>
            <div class="col-md-12">
                <img src="logo1.png" alt="logo">
            </div>
        </body>
    </html>