<?php
  ob_start();
?>
<?php
	echo '
		<footer class="page-footer grey lighten-1">
          <div class="container">
            <div class="row">
              <div class="col s12">
                <h5 class="white-text">Feito por Gustavo de Paula</h5>
                <p class="grey-text text-lighten-4">Licensiado pela GPL v3</p>
              </div>
            </div>
          </div>
        </footer>

	'

?>