<?php
  ob_start();
?>
<?php
	echo '
		<footer class="page-footer black">

 <div class="container">
  <div class="col s12">

  <h5 class="white-text">Dellareti 2018. All Rights Reserved</h5>        
        <ul class="list-inline">
          <la class="list-inline-item">
            <a href="#"> Privacy </a>
          </la>
          <la class="list-inline-item">
            <a href="#"> Terms </a>
          </la>
          <la class="list-inline-item">
            <a href="#"> FAQ </a>
          </la>
        </ul>
      </div>
 </div>
      </footer>

	' 
?>