<header class="menu" style="
    color: aliceblue;
    background: #222;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-end;
    align-items: flex-end;
    padding:12px;
">
    <ul style="display: flex; flex-wrap: wrap; width: 100%; justify-content: right;">
        <li style="list-style: none; font-size: 1.2em; margin-right: 10px;"><a href="views/phps/login.php" style="color: aliceblue; text-decoration: none; display: block; padding: 10px; transition: 80ms;" onMouseOver="this.style.transform='scale(1.16)'" onMouseOut="this.style.transform='scale(1)'"><i class="fa fa-sign-in"></i></a></li>
        <li style="list-style: none; font-size: 1.2em; margin-right: 10px;"><a href="views/phps/logout.php" style="color: aliceblue; text-decoration: none; display: block; padding: 10px; transition: 80ms;" onMouseOver="this.style.transform='scale(1.16)'" onMouseOut="this.style.transform='scale(1)'"><i class="fa fa-sign-out"></i></a></li>
        <li style="list-style: none; font-size: 1.2em; margin-right: 10px;"><a href="user.php/" style="color: aliceblue; text-decoration: none; display: block; padding: 10px; transition: 80ms;" onMouseOver="this.style.transform='scale(1.16)'" onMouseOut="this.style.transform='scale(1)'"><i class="fa fa-user-circle"></i></a></li>
    </ul>
</header>