<html>
    <head>
        <h1>Parabeins!!!! Vc ganhou R$000,000,000.00!!!!</h1>
        <h6>E ainda olhou o código pra conseguir chegar no final hein safado</h6>
        <h2>epa epa fessor desculpa o linguajar ae</h2>

        <h6>parabens por chegar no final ae<br>e por aguntar nois tmb<br> ah si e pelo filho tmb, sim sim parabens</h6>
        <br>
        <input type="submit" value="voltar">
        <input type="submit" name="acao" value="logout">
    </head>
</html>