<html>
    <body>
        <form method="post">
            <h3>Insira seus dados:</h3><br>
            <input type="text" placeholder="Login" name="login"><br>
            <input type="text" placeholder="Nome" name="nome"><br>
            <input type="password" placeholder="Senha" name="senha"><br>
            <input type="email" placeholder="Email" name="email"><br>
            <input type="hidden" name="indexPerguntaAtual" value="0"><br>
            <input type="submit" name ="enviar">
        </form>
    </body>
</html>