<html>
    <body>
        <form action="" method="post">
            <input type="text" placeholder="Login" name="login">
            <input type="text" placeholder="Nome" name="nome">
            <input type="password" placeholder="Senha" name="senha">
            <input type="email" placeholder="Email" name="email">
            <input type="hidden" name="indexPerguntaAtual" value="0">
            <input type="submit" name ="enviar">
        </form>
    </body>
</html>