<div class='form'>
    <h2> CADASTRO </h2>
    <form action='../../gerenciadores/cadastroLogin.php' method='POST'>
    <div class='login'>
        <label> <input type='text' name='nome'> Insira seu nome </label>
    </div>
    <div class='login'>
        <label> <input type='text' name='email'> Insira seu email </label>
    </div>
    <div class='login'>
        <label> <input type='text' name='login'> Insira seu login </label>
    </div>
    <div class='login'>
        <label> <input type='text' name='senha'> Insira sua senha </label>
    </div>
    <input class='pergunta' type='submit' name='resp'>
</div>

<?php 
    
   
?>