<nav class="navbar navbar-light bg-light">
    <div class="offset-4 row">
        <a class="" href="/">
            <img id="claquete" src="/assets/claquete.png" width="70" height="70" class="align-self-center" alt="">
        </a>
        <h1 id="title" class="text-center d-none d-sm-block ml-5 mt-3" >Show do Bilhão, Cinema Edition</h1>
        <h1 id="Points" class="ml-5 my-3" >Points: 17</h1>
        <button id="logoff" type="button" name="button" class="ml-5 my-3 btn">Sair</button>
    </div>

</nav>
