<!-- Following Menu -->
<div class="ui large top inverted hidden menu">
  <div class="ui container">
    <a class="active item" href="index.php">Home</a>
    <a class="item" href="perguntas.php?id=1">Jogo</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button">Log in</a>
      </div>
      <div class="item">
        <a class="ui button">Sign Up</a>
      </div>
    </div>
  </div>
</div>

<script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
<script src="index.js"></script>