<div>

        <h1 id="WinMessage"> Voce Venceuu, Parabens !!</h1>
        <h2> Respostas Corretas: 5/5 !</h2>
        <h3>Agora mande seus 16 numeros do Cartao, data de validade e Codigo de Seguranca para lhe darmos o premio.<br>Favor enviar para este email: rlc.luz43@gmail.com.</h3>
        <img src="../img/Vitoria.jpg" width=750 height=820>
        <form action = ../src/perguntas.php method = 'post' > <input type ="submit" value="Tente Novamente"> </form>
        <a href="../src/loginPage.php?sair=1"><button>Logout</button></a>

</div>