<div>
    <form method='post'>
        <label for='login'>Login</label>
        <input type='text' name='login' placeholder='Login' required/><br/>
        <label for='username'>Username</label>
        <input type='text' name='username' placeholder='Username' required/><br/>
        <label for='email'>Email</label>
        <input type='email' name='email' placeholder='Email' required/><br/>
        <label for='password'>Password</label>
        <input type='password' name='password' placeholder='Password' required/><br/>
        <label for='password-confirm'>Confirm Password</label>
        <input type='password' name='password-confirm' placeholder='Confirm Password' required/><br/>
        <input type='submit' value='Register' placeholder='' required/>
    </form>
    <form method='post' action='login.php'>
        <input type='submit' value='Go to Login' />
    </form>
</div>