<header>
            <nav class="navbar is-link">
                <div class="navbar-brand">
                        <a class="navbar-item" href="index.php">
                            <img src="images/show.jpg" alt="Show do bilhão, por Bryan Santos" width="112" height="100">
                        </a>
                        <div class="navbar-burger burger" data-target="navMenuColorinfo-example">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                <div id="navMenuColorinfo-example" class="navbar-menu">
                    <div class="navbar-start">
                    <a class="navbar-item" href="index.php">
                        Home
                    </a>
                    <a class="navbar-item" href="prova.php">
                        Prova de Conceito
                    </a>
                    </div>
                </div>
            </nav>
</header>