<?php 
    function exibeVitoria(){
        $telaVitoria = 
        '
        <img src="https://magazine25.vteximg.com.br/arquivos/ids/189718-550-550/Lettering-Transfer-para-Balao-Parabens-Preto-Parabens-22X18-cm----1-Unidade.jpg?v=637366580213800000" alt="Parabéns" width="200" height="200">
        <br>
        <p> 
            Parabéns pela vitória! Você respondeu as 5 perguntas corretamente!
            <br>
            <a href="index.php"> Voltar ao menu inicial </a>    
        </p>
        ';

        return $telaVitoria;
    }
?>