<hr>
<form action='realizar_cadastro.php' method='POST'>
    <fieldset>
        <legend>Nova Conta</legend>
        <label for='name'>Nome</label>
        <input type='text' name='name'></input><br>
        <label for='email'>E-mail</label>
        <input type='text' name='email'></input><br>
        <label for='user'>Usuario</label>
        <input type='text' name='user'></input><br>
        <label for='passwd'>Senha</label>
        <input type='password' name='passwd'></input><br>
        <input type='submit' value='Criar' />
    </fieldset>
</form>
<hr>