<?php

// class User{


//         // Properties
//         private $name;
//         private $username;
//         private $email;
//         private $password;

//         // Constructor
    
//         function __construct($name, $username, $email, $password)
//         {
//             $this->enunciado = $enunciado;
//             $this->alternativas = $alternativas;
//             $this->alternativa_correta = $alternativa_correta;
//         }


// }




?>